FROM alpine:3.13.5
LABEL version="20210511" \
      maintainer="Ozan Orcunus" \
      github="https://github.com/orcunuso/docker-images"

ENV POD_TIMEOUT=1440
RUN set -ex \
    && echo "http://nl.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories \
    && apk update \
    && apk add --no-cache \
         tcpdump \
         openssl \
         busybox-extras \
         bridge-utils \
         bind-tools \
         netcat-openbsd \
         util-linux \
         iptables \
         iputils \
         iproute2 \
         iftop \
         drill \
         apache2-utils \
         strace \
         curl \
         ethtool \
         ipvsadm \
         ngrep \
         iperf3 \
         nmap \
         nmap-nping \
         conntrack-tools \
         socat \
         git

RUN mkdir /netshoot \
    && chgrp -R 0 /netshoot \
    && chmod -R g=u /netshoot

ADD . /netshoot/
WORKDIR /netshoot
USER 10001
CMD ["sh","./bin/run.sh"]

# docker build -t docker.io/orcunuso/netshoot:alpine-20210511 -f Dockerfile-alpine .
