FROM alpine:3.11.6
LABEL version="20200501" \
      maintainer="Ozan Orcunus" \
      github="https://github.com/vOrcunus/docker-images"

ENV POD_TIMEOUT=120
RUN set -ex \
    && echo "http://nl.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories \
    && apk update \
    && apk add --no-cache \
         tcpdump \
         bridge-utils \
         bind-tools \
         netcat-openbsd \
         util-linux \
         iptables \
         iputils \
         iproute2 \
         iftop \
         drill \
         apache2-utils \
         strace \
         curl \
         ethtool \
         ipvsadm \
         ngrep \
         iperf3 \
         nmap \
         nmap-nping \
         conntrack-tools \
         socat \
         git

RUN mkdir /netshoot \
    && chgrp -R 0 /netshoot \
    && chmod -R g=u /netshoot

ADD . /netshoot/
WORKDIR /netshoot
USER 10001
CMD ["sh","./bin/run.sh"]

# docker build -t docker.io/orcunuso/netshoot:alpine-20200501 -f Dockerfile-alpine .
